# HALAMAN PERNYATAAN KEASLIAN KARYA SKRIPSI {.unnumbered}

Yang bertanda tangan di bawah ini:

| | | |
|:--|:--|:--|
| Nama          | : | Dimas Maulana |
| NIM           | : | 2215354026 |
| Program Studi | : | Sarjana Terapan Teknologi Rekayasa Perangkat Lunak |
| Jurusan       | : | Teknik Informasi |

dengan ini menyatakan dengan sebenar-benarnya bahwa skripsi yang berjudul:

::: {style="text-align: center"}
**"PERANCANGAN SISTEM PENDETEKSI KECURANGAN PADA PLATFORM GZCTF MENGGUNAKAN ALGORITMA TWO-STAGE SIMILARITY ANALYSIS DAN WEIGHTED RISK SCORING"**
:::

adalah benar-benar hasil karya saya sendiri dan bukan merupakan plagiat dari karya orang lain.
Hal-hal yang bukan merupakan karya saya dalam skripsi ini telah disebutkan sumbernya
dalam daftar pustaka sesuai dengan kaidah penulisan ilmiah.

Apabila di kemudian hari terbukti bahwa pernyataan ini tidak benar, saya bersedia menerima
sanksi akademik sesuai dengan ketentuan yang berlaku di Politeknik Negeri Bali, termasuk
pencabutan gelar yang telah diperoleh.

Demikian pernyataan ini saya buat dengan penuh kesadaran dan tanpa paksaan dari pihak mana pun.

<br>

::: {style="text-align: right"}

Jimbaran, ............... 2026

Yang menyatakan,

<br>

*(Materai Rp10.000)*

<br>

**Dimas Maulana**

NIM. 2215354026

:::

{{< pagebreak >}}
